### ISSUE TITLE
Error con el nerd fonts (polybar)

### ISSUE THREAD

**Issue by systemopped666** [darch7/bspwmbydarch#5]
Lo que pasa es que al abrir polybar con todas sus fuentes instaladas no funciona el caracter especial para tener las esquinas redondeadas, soy noob en todo esto, pd uso arch y bspwm :P
![image](https://user-images.githubusercontent.com/76662539/106225007-8fec5500-61e4-11eb-96ea-7ccb3614df49.png)

**Comment by darch7** [comment]
si funciona tienes todo, al parecer es que no copio a lo de la carpeta home, copia todo lo que está adentro y pégalo en tu home , abre terminal y escribe temas y debería aplicarse todo luego recarga el wm y ya

**Comment by darch7** [comment]
era un error del script que solucione ayer a la noche.
